server:
  servlet:
    context-path: /api
hsr:
  db:
    pw:
      file: /opt/hsr/vol/dbpw
  auth:
    jwt:
      expiration: 86400000
      secret:
        file: /opt/hsr/vol/jwtsecret
  resource:
    path: /opt/hsr/vol/resources